// Builds ahara/data/world.js: country facts and ready-to-draw SVG map paths.
// Needs: npm i world-atlas@2 topojson-client@3 d3-geo@3 world-countries@5
// Run:   NODE_PATH=<dir with node_modules> node ahara/tools/build_world.js
const fs = require("fs");
const path = require("path");
const topo = require("topojson-client");
const d3 = require("d3-geo");
const countries = require("world-countries");
const atlas = require("world-atlas/countries-110m.json");

const W = 1000, H = 520;
const features = topo.feature(atlas, atlas.objects.countries).features;
const projection = d3.geoNaturalEarth1().fitExtent([[6, 6], [W - 6, H - 6]], { type: "Sphere" });
const geoPath = d3.geoPath(projection).digits(1);

const CONTINENT = c => {
  if (c.region === "Americas") return c.subregion === "South America" ? "South America" : "North America";
  if (c.region === "Antarctic") return "Antarctica";
  return c.region; // Africa, Asia, Europe, Oceania
};
const byNum = new Map(countries.map(c => [c.ccn3, c]));
const byName = new Map(countries.map(c => [c.name.common, c]));
const ALIASES = { "Kosovo": "Kosovo", "N. Cyprus": null, "Somaliland": null, "W. Sahara": "Western Sahara" };

const facts = {};
const src = path.join(__dirname, "src", "country-facts.txt");
if (fs.existsSync(src)) {
  for (const line of fs.readFileSync(src, "utf8").split("\n")) {
    if (!line.trim() || line.startsWith("#")) continue;
    const [code, things, fact] = line.split("|").map(s => s.trim());
    facts[code] = { things: things ? things.split(",").map(s => s.trim()).filter(Boolean) : [], fact: fact || "" };
  }
}

const shapes = new Map();
for (const f of features) {
  let c = byNum.get(f.id);
  if (!c) {
    const alias = ALIASES[f.properties.name];
    c = alias === null ? null : byName.get(alias || f.properties.name);
  }
  const d = geoPath(f);
  if (!d) continue;
  if (!c) { shapes.set("_" + f.properties.name, { d }); continue; }
  // Frame the country on its biggest piece of land, so France is framed on
  // Europe rather than stretched out to French Guiana.
  const parts = f.geometry.type === "MultiPolygon"
    ? f.geometry.coordinates.map(coordinates => ({ type: "Polygon", coordinates })) : [f.geometry];
  const main = parts.reduce((a, b) => d3.geoArea(b) > d3.geoArea(a) ? b : a);
  const [[x0, y0], [x1, y1]] = geoPath.bounds(main);
  const prev = shapes.get(c.cca2);
  shapes.set(c.cca2, { d: prev ? prev.d + d : d, box: [x0, y0, x1, y1].map(v => Math.round(v * 10) / 10) });
}

const include = c => c.unMember || ["VA", "PS", "XK", "TW", "GL"].includes(c.cca2) || shapes.has(c.cca2);
const cca3 = new Map(countries.map(c => [c.cca3, c.name.common]));
const out = countries.filter(include).map(c => {
  const s = shapes.get(c.cca2);
  const row = {
    c: c.cca2, n: c.name.common, cap: (c.capital || []).join(", "), k: CONTINENT(c), sub: c.subregion,
    f: c.flag, lang: Object.values(c.languages || {}).slice(0, 3),
    cur: Object.values(c.currencies || {}).map(x => x.name + (x.symbol ? ` (${x.symbol})` : "")).slice(0, 2),
    area: Math.round(c.area), ll: c.latlng.map(v => Math.round(v * 10) / 10), land: c.landlocked ? 1 : 0,
    nb: (c.borders || []).map(b => cca3.get(b)).filter(Boolean), ind: c.independent === false ? 0 : 1
  };
  if (s) { row.d = s.d; row.box = s.box; }
  else { const [x, y] = projection([c.latlng[1], c.latlng[0]]); row.dot = [Math.round(x * 10) / 10, Math.round(y * 10) / 10]; }
  if (facts[c.cca2]) Object.assign(row, { things: facts[c.cca2].things, fact: facts[c.cca2].fact });
  return row;
}).sort((a, b) => a.n.localeCompare(b.n));

const other = [...shapes.entries()].filter(([k]) => k.startsWith("_")).map(([, v]) => v.d);
const sphere = geoPath({ type: "Sphere" });
const graticule = geoPath(d3.geoGraticule10());
// Map frames for zooming to each continent, as [west, south, east, north] in degrees.
const FRAMES = {
  "Africa": [-20, -36, 55, 38], "Asia": [25, -12, 150, 60], "Europe": [-25, 34, 45, 71],
  "North America": [-170, 7, -50, 75], "South America": [-85, -57, -32, 14], "Oceania": [110, -48, 180, 0],
  "Antarctica": [-180, -90, 180, -60]
};
const zoom = {};
for (const [k, [w, s2, e, n]] of Object.entries(FRAMES)) {
  const ring = [];
  for (let i = 0; i <= 20; i++) { const lon = w + (e - w) * i / 20; ring.push(projection([lon, s2]), projection([lon, n])); }
  for (let i = 0; i <= 20; i++) { const lat = s2 + (n - s2) * i / 20; ring.push(projection([w, lat]), projection([e, lat])); }
  const xs = ring.map(p => p[0]), ys = ring.map(p => p[1]);
  zoom[k] = [Math.min(...xs), Math.min(...ys), Math.max(...xs), Math.max(...ys)].map(v => Math.round(v));
}
const data = { W, H, sphere, graticule, other, zoom, countries: out };
const file = path.join(__dirname, "..", "data", "world.js");
fs.writeFileSync(file, "// Generated by tools/build_world.js from world-atlas (Natural Earth, public domain)\n// and world-countries (ODbL). Edit tools/src/country-facts.txt, then rebuild.\n" +
  "window.AHARA_WORLD = " + JSON.stringify(data) + ";\n");
console.log(out.length, "countries,", out.filter(c => c.d).length, "with shapes,", out.filter(c => c.things).length, "with facts;", (fs.statSync(file).size / 1024).toFixed(0) + " KB");
